Script to generate the reference sequence file for 100 individuals, 90 of them randomly having the reference allele and 10 having the alternative (MAF=0.1)

In [494]:
ref_file = "/Users/dmc2245/Documents/Cornejo_Diana/family-association/seqsimla/input/ref_file.txt"

In [495]:
#f = open(ref_file, 'w')
#import random
#my_list = ([0]*900 + [1]*100)
#random.shuffle(my_list)
#print(*my_list, sep = '\n', file = f)

Script to generate the `ref_file.txt` with 4 variants and 1000 individuals, where the frequency of the variants follows a random binomia distribution with a MAF=0.1. Use `x.transpose` to change the matrix orientation

In [ ]:
import numpy as np
output_haplos = open(ref_file, 'w')
haplos = np.random.binomial(1, 0.1, (1000, 4))
#haplos.transpose()
for row in haplos:
    for elem in row:
        print(elem, end='')
    print()
np.savetxt(output_haplos, haplos, fmt="%.0f", delimiter="")
output_haplos.close()
 

0001
0000
0000
0000
0000
0000
1000
0000
0000
0000
0001
0000
1000
0000
0000
0010
0000
0011
0000
1000
0000
0000
0000
0010
0000
0000
0000
0101
0100
0000
0001
0000
0010
1000
0000
0000
0001
0000
0000
0000
0000
1000
0000
0000
0000
0000
0000
0000
1000
0000
0100
0000
1000
0000
0001
0000
0010
0000
0110
0111
0000
0001
0000
0000
0000
0000
0001
0000
0000
0001
0001
0000
0100
0000
0000
0000
0001
0000
0100
0000
0000
0001
0000
0110
0100
0010
0000
0000
0100
0000
0000
0000
0000
0000
0001
0000
0000
0010
0010
0000
0000
0001
0000
0000
0010
1000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
1010
0100
0000
0000
0000
0000
0000
0010
0010
0010
0000
1000
0000
0100
0000
0000
0000
1000
0000
0000
0000
0010
1000
0000
0010
0000
0000
0001
0000
0000
0100
0000
0010
0000
0000
1000
1000
0100
0000
0000
0000
0001
0100
0000
0000
0000
0000
1010
0000
0000
1000
1100
0000
0000
0000
0000
0000
0001
0000
0000
0000
0000
0100
0010
0100
1000
0010
0100
1100
0010
0001
0001
0000
0000
0000
0000
0000
0000
0000
0000


IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



000
0000
0010
0000
0000
0010
1000
0000
0000
0100
0010
0000
0000
1001
0000
1001
0000
0100
0000
0000
0000
0100
0000
0000
0100
1000
0000
0000
1010
0000
0000
0000
0000
0000
0000
0001
0000
0000
0000
0010
0000
0000
0000
0000
0001
0000
0000
0000
0000
0010
0011
0

In [497]:
np.mean(haplos, axis=0)

array([0.095, 0.106, 0.111, 0.094])

In [423]:
haplos

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       ...,
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [425]:
haplos.transpose()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [432]:
np.mean(haplos.transpose(), axis=1)

array([0.108, 0.099, 0.091, 0.106])

In [ ]:
d = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
for col in d:
    for elem in col:
        print(elem, end=' ')
    print()

In [334]:
s = np.array(([[5, 3], [1, 8]]))
np.mean(s) #perfoms the mean in the whole matrix

4.25

In [335]:
np.mean(s, axis=0) #uses the columns of the matrix to calculate the mean

array([3. , 5.5])

In [336]:
np.mean(s, axis=1) #uses the rows of the matrix to calculate the mean

array([4. , 4.5])