## Input files generated for SeqSIMLA: haplotype file

Here I generated the reference sequence file for 1000 individuals, 900 of them randomly having the reference allele and 100 having the alternative (MAF=0.1)
**Note:** SeqSIMLA haplotype file does not allow less than 4 variant sites

In **Diana's mac** files are stored in `/Users/dianacornejo/family-association`

In **work mac** files are stored in  `/Users/dmc2245/Documents/Cornejo_Diana/family-association/`

In [10]:
pwd

/Users/dianacornejo/family-association


In [17]:
ref_file = "/Users/dianacornejo/family-association/seqsimla/input/ref_file.txt"

In [495]:
#f = open(ref_file, 'w')
#import random
#my_list = ([0]*900 + [1]*100)
#random.shuffle(my_list)
#print(*my_list, sep = '\n', file = f)

Script to generate the `ref_file.txt` with 4 variants and 1000 individuals, where the frequency of the variants follows a random binomial distribution with a MAF=0.1. Use `x.transpose` to change the matrix orientation

In [20]:
import numpy as np
output_haplos = open(ref_file, 'w')
haplos = np.random.binomial(1, 0.1, (1000, 4))
#haplos.transpose()
for row in haplos:
    for elem in row:
        print(elem, end='')
    print()
np.savetxt(output_haplos, haplos, fmt="%.0f", delimiter="")
output_haplos.close()
 

0000
0001
0000
1010
1100
0000
0000
0000
1000
0000
0011
0000
0000
0000
0000
0000
0010
0001
0000
0000
0000
0000
0000
1000
0000
0000
0001
0000
0001
0000
0100
0000
0001
0000
1010
1000
0100
0000
0000
0001
0000
0001
1000
0000
0010
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0001
0000
1010
0000
0100
0000
0000
0000
0000
0001
0010
0000
0000
0010
0000
0000
0000
0100
1000
0000
0000
0000
0100
0000
0000
0000
0000
0000
0000
0000
0100
0100
1000
1000
0000
0000
0000
0000
0000
0000
1000
1001
0100
1000
0000
0000
0000
0001
0000
0000
1100
0100
0000
0000
0000
1000
0100
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0000
0001
0100
0010
0000
0100
1000
1010
1000
0000
1001
1010
0000
0000
0000
0000
1000
0000
0011
0001
0000
0101
1000
0000
0000
0000
0000
1000
0000
0010
0000
1000
0000
1000
0100
0010
0000
0000
1000
0000
0000
0001
0010
0001
0000
0000
0000
0000
1000
0000
0010
0000
0000
0100
0000
0000
0000
0000
1000
0000
0000
0000
0000
0000
0010
0000
0000
0010
0000
0000
0010
0000
1000


In [22]:
np.mean(haplos, axis=0) #uses the columns of the matrix

array([0.115, 0.103, 0.113, 0.095])

From this part downwards is only to understand how matrices and operations with matrices work

In [23]:
haplos

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       ...,
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
haplos.transpose()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [25]:
np.mean(haplos.transpose(), axis=1) #uses the rows of the transposed matrix 

array([0.115, 0.103, 0.113, 0.095])

In [26]:
d = [[1, 2, 3, 4], [5, 6], [7, 8, 9]]
for col in d:
    for elem in col:
        print(elem, end=' ')
    print()

1 2 3 4 
5 6 
7 8 9 


In [27]:
s = np.array(([[5, 3], [1, 8]]))
np.mean(s) #perfoms the mean in the whole matrix

4.25

In [28]:
np.mean(s, axis=0) #uses the columns of the matrix to calculate the mean

array([3. , 5.5])

In [29]:
np.mean(s, axis=1) #uses the rows of the matrix to calculate the mean

array([4. , 4.5])