Script to generate the reference sequence file for 100 individuals, 90 of them randomly having the reference allele and 10 having the alternative (MAF=0.1)

In [211]:
filename = "/Users/dmc2245/Documents/Cornejo_Diana/family-association/seqsimla/input/ref_file.txt"
f = open(filename, 'w')
import random
my_list = ([0]*900 + [1]*100)
random.shuffle(my_list)
print(*my_list, sep = '\n', file = f)
f.close()

In [170]:
filename = "ref_file1.txt"
f1 = open(filename, 'w')
my_list2 = ([0]*90 + [1]*10,[0]*50 + [1]*50)
my_list2
#print(my_list2)
print(*my_list2, file = f1)

In [57]:
import numpy as np
random_matrix_array = np.random.randint(2,size=(4,4))
print(random_matrix_array)

[[1 1 1 0]
 [0 1 0 1]
 [1 1 1 1]
 [1 1 0 0]]


In [68]:
rows, cols = (10,2)
arr = [[(np.random.binomial(1,0.1)) for i in range(cols)]] 
arr

[[0, 0]]

In [60]:
random.randint(0, 1)

1

In [173]:
y = np.random.binomial([0,1], p=[0.6, 0.4], size=(10, 1))
print(y)

[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]]


In [219]:
import numpy as np
ref = np.tile(np.random.randint(0, 2, size=(100, 1)),4)
print (ref, sep = '')

[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]

In [209]:
a = np.random.binomial(1, .5, (10, 1))
a

array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1]])